(function(I){'use strict';
const $=id=>document.getElementById(id),KEY='idol-longrun-season-040',PREF='idol-longrun-prefs-040';
let s=I.newGame(),saved=null,busy=false,auto=false,timer=null,lastFocus=null,storageOK=true,prefs={motion:true,haptic:false};
try{const v=JSON.parse(localStorage.getItem(KEY));if(I.validSave(v))saved=v;const p=JSON.parse(localStorage.getItem(PREF));if(p)prefs={motion:p.motion!==false,haptic:!!p.haptic};}catch(e){storageOK=false;}
const reduced=()=>!prefs.motion||matchMedia('(prefers-reduced-motion: reduce)').matches;
function save(){if(!I.validSave(s))return;try{localStorage.setItem(KEY,JSON.stringify(s));saved=I.clone(s);storageOK=true;}catch(e){storageOK=false;}}
function vibrate(){if(prefs.haptic&&navigator.vibrate)try{navigator.vibrate(9);}catch(e){}}
function render(){const V=I.V;let html=s.screen==='home'?V.home(saved):s.screen==='routes'?V.routes(s):s.screen==='intro'?V.intro(s,auto):s.screen==='choice'?V.choice(s,auto):s.screen==='result'?V.result(s):V.ending(s);$('view').innerHTML=html;$('app').dataset.screen=s.screen;if(auto&&s.screen==='ending')stopAuto();if(!reduced()){$('view').firstElementChild?.animate([{opacity:.55,transform:'translateY(5px)'},{opacity:1,transform:'translateY(0)'}],{duration:190,easing:'ease-out'});}if(s.screen==='result')animateNumbers();}
function animateNumbers(){if(reduced())return;for(const el of document.querySelectorAll('[data-result-key]')){const from=Number(el.dataset.from),to=Number(el.dataset.to),key=el.dataset.resultKey,start=performance.now();function tick(now){if(!el.isConnected)return;const p=Math.min(1,(now-start)/420);el.textContent=I.value(key,I.round(from+(to-from)*(1-Math.pow(1-p,3))));if(p<1)requestAnimationFrame(tick);}requestAnimationFrame(tick);}}
function fx(rect){if(reduced()||!rect||s.screen!=='result')return;const layer=$('fx');layer.replaceChildren();const first=s.last.rows[0];const target=first&&document.querySelector(`[data-result-key="${first.key}"]`);if(target){const t=target.getBoundingClientRect(),el=document.createElement('span');el.className='fly-number';el.textContent=I.V.sign(first.key,first.delta);el.style.left=rect.x+rect.width/2+'px';el.style.top=rect.y+rect.height/2+'px';layer.append(el);const a=el.animate([{transform:'translate(-50%,-50%) scale(.8)',opacity:0},{offset:.15,transform:'translate(-50%,-70%) scale(1.05)',opacity:1},{transform:`translate(${t.x-rect.x-rect.width/2}px,${t.y-rect.y-rect.height/2}px) scale(.8)`,opacity:0}],{duration:600,easing:'ease-out'});a.onfinish=()=>el.remove();}
if(s.last.notes.some(n=>n.includes('해금')||n.includes('통과'))){const x=rect.x+rect.width/2,y=rect.y+rect.height/2;for(let i=0;i<12;i++){const el=document.createElement('i');el.className='particle'+(i%3===0?' pink':'');el.style.left=x+'px';el.style.top=y+'px';layer.append(el);const angle=i*Math.PI/6,d=30+Math.random()*50;el.animate([{transform:'translate(0,0)',opacity:1},{transform:`translate(${Math.cos(angle)*d}px,${Math.sin(angle)*d}px)`,opacity:0}],{duration:550+Math.random()*160,easing:'ease-out'}).onfinish=()=>el.remove();}}}
function run(action,button){if(busy)return;busy=true;const rect=button?.getBoundingClientRect();action();save();render();fx(rect);vibrate();$('live').textContent=s.screen==='result'?s.last.title+' 결과. '+s.last.rows.map(r=>I.labels[r.key]+' '+I.V.sign(r.key,r.delta)).join(', '):'';setTimeout(()=>{busy=false;},reduced()?35:210);}
function stopAuto(){auto=false;clearTimeout(timer);timer=null;document.querySelectorAll('[data-do=auto]').forEach(b=>{b.textContent='▷ 자동 진행';b.setAttribute('aria-pressed','false');});}
function schedule(){clearTimeout(timer);if(!auto)return;timer=setTimeout(()=>{if(document.hidden||$('info').open||matchMedia('(orientation:landscape) and (max-height:520px)').matches){stopAuto();return;}if(s.screen==='ending'){stopAuto();return;}if(!busy){if(s.screen==='choice')run(()=>I.choose(s,I.autoChoice(s)));else if(['intro','result'].includes(s.screen))run(()=>I.next(s));}schedule();},s.screen==='result'?1500:1100);}
function tabs(active){return ['stats','tags','history','money'].map((t,i)=>`<button data-tab="${t}" aria-selected="${active===t}">${['상태','효과','기록','정산'][i]}</button>`).join('');}
function openInfo(kind){stopAuto();lastFocus=document.activeElement;$('info-title').textContent=kind==='last'?'선택 결과 다시 보기':kind==='dialogue'?'제안 다시 듣기':kind==='settings'?'설정':'내 커리어';$('tabs').innerHTML=['stats','tags','history','money'].includes(kind)?tabs(kind):'';$('info-body').innerHTML=I.infoContent(s,prefs,storageOK,kind);if(!$('info').open)$('info').showModal();$('info-body').scrollTop=0;}
function closeInfo(){if($('info').open)$('info').close();if(lastFocus?.isConnected)lastFocus.focus();}
function newLife(name){stopAuto();if(saved&&saved.screen!=='ending'&&!confirm('진행 중인 커리어 대신 새 인생을 시작할까요? 새 루트를 고르면 저장이 교체됩니다.'))return;closeInfo();s=I.newGame(name||'하린');s.screen='routes';render();}
$('view').addEventListener('submit',e=>{if(e.target.id==='start-form'){e.preventDefault();newLife($('player-name').value);document.activeElement?.blur();}});
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.info){openInfo(b.dataset.info);return;}if(b.dataset.tab){openInfo(b.dataset.tab);return;}if(b.classList.contains('close-info')){closeInfo();return;}if(b.dataset.route){run(()=>I.start(s,b.dataset.route),b);return;}if(b.dataset.choice){run(()=>I.choose(s,b.dataset.choice),b);return;}switch(b.dataset.do){case 'next':run(()=>I.next(s),b);break;case 'auto':auto=!auto;render();schedule();break;case 'resume':if(saved){s=I.clone(saved);render();}break;case 'home':stopAuto();closeInfo();s=I.newGame();render();break;case 'new':newLife(s.name);break;}});
$('menu').addEventListener('click',()=>openInfo('settings'));
$('info').addEventListener('click',e=>{if(e.target===$('info')){const r=$('info').getBoundingClientRect();if(e.clientY<r.top||e.clientX<r.left||e.clientX>r.right)closeInfo();}});
$('info').addEventListener('change',e=>{const key=e.target.dataset.pref;if(key){prefs[key]=e.target.checked;try{localStorage.setItem(PREF,JSON.stringify(prefs));}catch(e){}}});
document.addEventListener('visibilitychange',()=>{if(document.hidden){stopAuto();save();}});
function resize(){const v=window.visualViewport,h=v&&v.scale===1?v.height:innerHeight;document.documentElement.style.setProperty('--vh',Math.round(h)+'px');if(innerWidth>innerHeight&&innerHeight<520)stopAuto();}window.addEventListener('resize',resize);window.visualViewport?.addEventListener('resize',resize);window.addEventListener('pagehide',save);resize();render();
I.UI={getState:()=>I.clone(s),isBusy:()=>busy};
if(globalThis.__IDOL_QA__===true||new URLSearchParams(location.search).has('qa'))I.UI.fixture=state=>{stopAuto();s=I.clone(state);busy=false;render();};
})(globalThis.ILR);
