(function(I){'use strict';const E=I.event,O=I.option;
E('ost',['career'],'NOVA A&R','음악사업 담당','목소리로 받은 OST 제안','{name} 씨, 메인보컬로 준비한 목소리를 듣고 OST 연락이 왔어요. 개인 녹음과 팀 활동 시간을 조율해야 합니다.','그때 보컬을 선택한 덕분에 생긴 기회다. 시간을 어디에 쓸까?',[
O('solo','개인 OST를 녹음한다',{v:4,brand:5,cash:3,energy:-7},{tag:'live',future:'라이브 음원 제안 해금'}),O('duet','팀 멤버와 듀엣을 제안한다',{v:2,team:7,fans:2},{tag:'trusted',future:'개인 노출 대신 팀의 신뢰'}),O('next','다음 곡을 기약한다',{energy:8,stress:-5},{future:'기회보다 현재 컨디션을 지킴'})],{need:'vocal',priority:5});
E('choreo',['career'],'NOVA 퍼포먼스팀','공연 감독','직접 만드는 댄스 브레이크','퍼포먼스 리더로서 보여준 감각이 좋았어요, {name} 씨. 이번 무대의 안무를 직접 만들어볼래요?','시키는 동작을 넘어서, 내 무대를 만들 수 있을까?',[
O('make','직접 안무를 만든다',{d:6,brand:4,stress:6},{buff:{stat:'fans',rate:.3,duration:2},future:'다음 2시즌 팬 증가 +30%'}),O('team','멤버들과 공동 제작한다',{d:3,team:8,energy:-4},{tag:'trusted',future:'유닛 제안 해금'}),O('coach','전문 안무가에게 배운다',{d:4,debt:2},{buff:{stat:'d',rate:.4,duration:2},future:'다음 2시즌 댄스 성장 +40%'})],{need:'dancer',priority:5});
E('cover',['career'],'NOVA 광고사업팀','브랜드 매니저','센터에게 온 표지 촬영','센터 테스트 영상을 보고 잡지에서 연락이 왔어요. {name} 씨를 단독 표지에 세우고 싶대요.','화려한 노출이 내 팬으로 이어질까, 팀에서 멀어질까?',[
O('cover','단독 표지를 촬영한다',{look:4,brand:6,cash:4,energy:-6},{future:'광고 수익 계산에 브랜드 반영'}),O('group','그룹 화보로 역제안한다',{team:7,fans:3,brand:2},{future:'개인 수익 대신 그룹 팬덤'}),O('wait','컴백 이후로 미룬다',{energy:7,stress:-4},{future:'노출을 쉬고 무대 준비'})],{need:'center',priority:5});
E('unit',['career'],'NOVA A&R','유닛 기획자','함께 일하고 싶은 멤버','팀 안에서 신뢰를 쌓아왔네요, {name} 씨. 멤버들이 작은 유닛 무대를 함께 하고 싶어 해요.','경쟁 대신 함께하기를 선택했던 일이 기회가 됐다.',[
O('unit','유닛 무대를 준비한다',{fans:4,team:5,energy:-6},{buff:{stat:'fans',rate:.3,duration:2},future:'다음 2시즌 팬 증가 +30%'}),O('teach','후배 무대를 도와준다',{rep:6,team:4},{tag:'selfcare',future:'생활 리듬을 지키는 장기관리'}),O('own','개인 무대에 집중한다',{v:5,team:-3},{future:'관계보다 개인 역량 우선'})],{need:'trusted',priority:4});
E('live-record',['career'],'NOVA 음악사업팀','라이브 제작 PD','라이브 음원 발매 제안','{name} 씨의 라이브를 다시 듣고 싶다는 반응이 있어요. 보정 없이 남기는 무대에 도전할까요?','한 번 쌓은 신뢰를 더 키울까, 부담을 줄일까?',[
O('raw','원테이크 라이브를 공개한다',{fans:[3,6],brand:4,energy:-7},{tag:'loyal',future:'코어 팬덤 · 팬 투어 해금'}),O('studio','스튜디오 라이브로 준비한다',{v:4,fans:2,debt:2},{future:'제작비로 안정성을 확보'}),O('small','소규모 공연부터 한다',{fans:3,stress:-4},{future:'노출보다 관객과의 거리'})],{need:'live',priority:4});
E('fan-tour',['career'],'NOVA 공연사업팀','투어 매니저','오래 기다린 팬들의 공연','꾸준히 소통한 팬들이 작은 투어를 원해요, {name} 씨. 큰 공연장과 가까운 무대 중 어디를 택할까요?','몇 명에게 보이느냐보다 누가 다시 올지가 중요해질까?',[
O('close','소극장 팬 투어를 연다',{fans:5,cash:4,energy:-6},{buff:{stat:'fans',rate:.3,duration:2},future:'다음 2시즌 팬 증가 +30%'}),O('large','큰 공연장에 도전한다',{fans:[2,7],brand:5,energy:-10,debt:3},{future:'추가 투자로 더 큰 관객에 도전'}),O('online','온라인 팬미팅으로 만난다',{fans:3,rep:3,energy:-2},{future:'수익보다 접근성과 컨디션'})],{need:'loyal',priority:4});
E('response',['career'],'NOVA 매니지먼트','담당 매니저','짧게 잘린 팬싸 영상','{call}, 어제 응대가 무성의해 보였다는 영상이 돌고 있어. 전체 맥락과 네 컨디션을 정리해 대응하자.','작은 신호일 때 관계를 회복할까, 더 지켜볼까?',[
O('explain','팬에게 직접 설명하고 사과한다',{rep:5,brand:-2,stress:3},{future:'평판을 지키되 당장 노출은 줄어듦'}),O('team','회사와 사실관계를 정리한다',{rep:2,cash:-1,stress:-3},{future:'시간과 비용으로 대응 부담 분담'}),O('ignore','반응을 더 지켜본다',{energy:4},{risk:{chance:.45,effect:{rep:-8,brand:-6}},future:'45% 확률로 인성 -8 · 브랜드 -6 추가'})],{condition:'risk',priority:8});
E('comeback',['career'],'NOVA A&R','컴백 프로듀서','익숙한 색과 새로운 콘셉트','{name} 씨, 팬들이 좋아하는 색을 이어갈까요? 회사는 새로운 콘셉트로 대중을 넓히는 안도 준비했어요.','지금 팬을 지키는 것과 새 팬을 만나는 것, 어느 쪽이 급할까?',[
O('new','새 콘셉트에 도전한다',{brand:6,fans:[1,5],stress:5},{future:'팬 반응은 +1~5만으로 변동'}),O('known','팬들이 좋아하는 색을 지킨다',{fans:4,brand:1},{tag:'loyal',future:'코어 팬덤 · 팬 투어 해금'}),O('rest','준비 기간을 늘린다',{v:3,d:3,energy:7,brand:-3},{future:'이번 노출 대신 완성도 확보'})]);
E('offer',['career'],'NOVA 광고사업팀','사업 담당자','빠듯한 일정의 광고 제안','{name} 씨, 광고 출연 제안이 왔어요. 정산에는 도움이 되지만 이미 잡힌 연습 시간을 조정해야 해요.','당장의 정산과 앞으로의 실력을 어떻게 나눌까?',[
O('all','전 일정을 수락한다',{cash:6,brand:4,energy:-10,stress:4},{future:'확정 정산 +600만 · 일정 부담'}),O('part','일부 일정만 수락한다',{cash:3,brand:2,energy:-4},{future:'수익과 컨디션 절충'}),O('no','연습 일정을 지킨다',{v:4,rep:2,energy:3},{future:'수익 대신 다음 무대 준비'})]);
E('private',['career'],'NOVA 매니지먼트','담당 매니저','사생활과 활동의 경계','{name} 씨, 외부 모임 제안이 많아졌죠. 누구를 만나든 사생활과 활동을 어떻게 구분할지 함께 정해두면 좋겠어요.','사람을 만나는 즐거움과 공개되는 삶의 부담을 함께 생각하자.',[
O('boundary','일정과 공개 범위를 정한다',{stress:-6,rep:2},{future:'사생활을 지키며 컨디션 관리'}),O('social','업계 모임에 적극 참여한다',{brand:4,stress:3,energy:-4},{future:'노출과 인맥에 시간을 투자'}),O('rest','당분간 개인 시간을 가진다',{energy:8,stress:-4,brand:-2},{future:'노출 대신 휴식'})],{minAge:18});
E('renewal',['career'],'NOVA 경영지원팀','계약 담당 임원','첫 재계약 테이블','{name} 씨, 함께한 시간이 쌓였네요. 수익 배분을 높이는 안과 장기 지원을 늘리는 안을 검토해보죠.','계약서의 숫자보다 앞으로 어떤 활동을 계속할지가 먼저일까?',[
O('share','수익 배분을 높인다',{stress:4},{tag:'renewal',future:'향후 아티스트 몫 50% → 60%'}),O('long','장기관리 지원을 받는다',{energy:12,rep:3},{tag:'selfcare',future:'회복 +20% · 장기관리 루틴'}),O('solo','솔로 전환을 협의한다',{brand:-5,team:-5},{tag:'solo',future:'향후 정산 인원 5명 → 1명'})],{minAge:25,priority:6,once:true});
E('rookie',['career'],'NOVA 매니지먼트','본부장','신인 푸쉬 이후의 자리','회사의 홍보 일정이 신인에게도 나뉘고 있어요, {name} 씨. 대중 노출을 다시 잡을지 기존 관객에 집중할지 정해봅시다.','새 얼굴과 같은 방식으로 경쟁해야만 오래갈 수 있을까?',[
O('public','대중 활동을 다시 늘린다',{brand:7,energy:-9,stress:4},{future:'노출 경쟁에 컨디션을 투자'}),O('fans','기존 팬을 관객으로 키운다',{fans:5,brand:-2},{tag:'loyal',future:'팬 투어 제안 해금'}),O('solo','나만의 솔로 무대를 준비한다',{v:4,brand:-3,debt:3},{tag:'solo',future:'향후 정산 인원 5명 → 1명'})],{minAge:30,priority:5,once:true});
E('dinner',['career'],'NOVA 공연사업팀','공연 기획 이사','디너쇼로 이어지는 무대','{name} 씨의 노래를 오래 들은 관객이 있어요. 이제 컴백 경쟁보다 이름을 걸고 오래 서는 공연을 만들어볼까요?','팬을 평생의 관객으로 바꿀 때가 온 걸까?',[
O('dinner','디너쇼 전환을 준비한다',{v:3,debt:6,brand:-4},{tag:'dinner',future:'공연 매출 +25% · 레전드 조건'}),O('tour','기존 투어를 유지한다',{fans:4,brand:3,energy:-8},{future:'익숙한 방식으로 활동 지속'}),O('teach','휴식하며 다음 무대를 준비한다',{rep:5,energy:12,brand:-3},{tag:'selfcare',future:'회복 +20% · 장기관리'})],{minAge:38,priority:7,once:true});
E('solo-record',['career'],'독립 프로젝트 A&R','앨범 프로듀서','처음으로 이름을 건 앨범','{name} 씨, 솔로 전환을 선택했으니 이제 곡도 직접 정해봅시다. 팀의 색이 아닌 당신의 목소리로요.','더 많이 결정할 수 있는 만큼, 결과도 내 몫이 된다.',[
O('own','직접 고른 곡을 녹음한다',{v:5,brand:4,debt:4},{tag:'live',future:'라이브 음원 제안 해금'}),O('popular','대중적인 곡을 선택한다',{fans:4,brand:5,stress:4},{future:'나만의 색보다 새로운 관객'}),O('small','소규모 라이브로 먼저 낸다',{fans:3,energy:-3},{tag:'loyal',future:'코어 팬덤 · 팬 투어 해금'})],{need:'solo',priority:5});
})(globalThis.ILR);
