(function(I){'use strict';
I.planOptions=s=>{if(I.stage(s)==='career'){let primary=s.tags.includes('center')?'ads':s.fans>=12&&s.season%2===1?'concert':'album';return [I.plans[primary],I.plans.fans,I.plans.care];}if(s.season===0)return [s.focusPlan,...['v','d','look'].filter(k=>k!==s.focusPlan)].map(k=>I.plans[k]);const keys=['v','d','look'];let main=keys.includes(s.focusPlan)?s.focusPlan:keys.reduce((a,b)=>s[a]>s[b]?a:b);if(s[main]>=95)main=keys.reduce((a,b)=>s[a]<s[b]?a:b);let other=keys.filter(k=>k!==main)[s.season%2];return [I.plans[main],I.plans[other],I.plans[s.energy<67||s.stress>40?'rest':'balance']];};
I.current=s=>{if(s.mode==='event')return I.events.find(e=>e.id===s.eventId);if(s.mode==='gate'){const cfg=I.gates[s.gate.at];return {...cfg,quote:`{name} 씨, 준비한 장점을 세 번의 어필로 보여주세요. 마지막에는 태도와 팀의 준비도도 함께 평가합니다.`,thought:'초반에 집중을 쌓을까, 컨디션을 남기며 점수를 낼까?',options:s.gate.hand.map(id=>I.gateCards.find(c=>c.id===id))};}
const route=I.routes.find(r=>r.id===s.route)||I.routes[0],stage=I.stage(s);let meta={...route,title:'첫 반년, 어떤 매력을 키울까?'};
if(s.season>0){const early=stage==='academy';meta={org:early?route.org:stage==='career'?'NOVA 매니지먼트':'NOVA 트레이닝팀',speaker:early?route.speaker:stage==='career'?'담당 매니저':'육성 담당자',title:stage==='career'?'이번 반년의 활동 방향':'이번 반년의 성장 방향',quote:s.energy<35?'{name} 씨, 지난 일정으로 컨디션이 많이 내려갔어요. 다음 반년의 속도를 다시 정해야겠어요.':stage==='career'?'{name} 씨, 이번 반년은 새로운 팬을 만날까요, 기다려준 관객을 챙길까요? 오래 설 수 있는 일정으로 정해봅시다.':'{call}, 지난 반년의 결과를 보고 다음 계획을 가져왔어. 장점을 더 밀지, 다른 가능성을 키울지 생각해보자.',thought:s.energy<35?'컨디션이 15 미만인 시즌이 세 번 쌓이면 활동을 이어가기 어렵다.':stage==='career'?'눈앞의 수익, 남는 팬, 오래갈 컨디션 중 무엇이 부족할까?':'한 분야의 성장과 다음 관문을 버틸 여유를 함께 보자.'};}
return {...meta,options:I.planOptions(s)};};
I.hand=s=>{const a=I.gateCards.map(c=>c.id),out=[];while(out.length<3)out.push(a.splice(Math.floor(I.random(s)*a.length),1)[0]);return out;};
I.gateBonus=s=>I.round(s.rep*.12+s.team*.08+(s.gate?.at===9?s.song*.15:0));
I.pickEvent=s=>{const stage=I.stage(s);let es=I.events.filter(e=>e.stages.includes(stage)&&(!e.minAge||I.age(s)>=e.minAge)&&(!e.need||s.tags.includes(e.need))&&(!e.plan||e.plan===s.focusPlan)&&(!e.condition||(e.condition==='risk'&&(s.stress>68||s.rep<50)))&&(!e.once||!s.eventSeen[e.id])&&(!s.eventSeen[e.id]||s.season-s.eventSeen[e.id].last>=8));
const urgent=es.filter(e=>e.condition||(!s.eventSeen[e.id]&&(e.need||e.priority>=5)));if(stage==='career'&&s.season%4!==2&&!urgent.length)return null;if(urgent.length)es=urgent;
const priority=e=>(!s.eventSeen[e.id]?20:0)+(e.priority||0)+(e.plan?2:0);es.sort((a,b)=>priority(b)-priority(a));if(!es.length)return null;const top=es.filter(e=>priority(e)===priority(es[0]));return top[Math.floor(I.random(s)*top.length)];};
I.start=(s,routeId)=>{if(s.screen!=='home'&&s.screen!=='routes')return false;const r=I.routes.find(r=>r.id===routeId);if(!r)return false;s.route=r.id;I.apply(s,r.effect);s.focusPlan=routeId==='dance'?'d':routeId==='casting'?'look':'v';s.seasonStart=I.metrics(s);s.mode='plan';s.screen='intro';I.log(s,r.name+' 입문',r.sub);return true;};
I.preparePlan=s=>{s.mode='plan';s.eventId=null;s.gate=null;s.seasonStart=I.metrics(s);s.screen=([0,1,2,4,8,10].includes(s.season)||s.season%2===0)?'intro':'choice';};
I.finish=s=>{s.screen='ending';const legend=s.tags.includes('dinner')&&s.rep>=70&&s.v>=70&&s.fans>=30;s.ending=s.ending||{title:legend?'디너쇼 레전드':'장수 아이돌',body:legend?'50세까지 목소리와 신뢰를 지켜, 팬을 평생의 관객으로 바꿨습니다.':'반세기의 문턱까지 현역 무대를 이어갔습니다. 당신의 선택이 만든 커리어입니다.'};I.log(s,s.ending.title,s.ending.body);};
I.advance=s=>{const before=I.metrics(s),oldStage=I.stage(s);s.season++;s.buffs=s.buffs.filter(b=>b.until>=s.season);if(s.season>=74){I.finish(s);return;}
if(s.season===4)s.debt+=8;if(s.season===8)s.song+=5;if(s.season===10){s.debt+=28;s.fans+=2;s.brand+=12;s.group='LUMINA';}I.clean(s);
if(I.stage(s)!==oldStage){s.last={title:I.stageName(s)+' 시작',actor:'NOVA 매니지먼트',rows:I.diff(before,I.metrics(s)),notes:[s.season===10?'LUMINA의 5인조 멤버로 데뷔했습니다. 준비 비용은 앞으로의 정산에서 갚습니다.':'새 단계의 준비 비용과 상태가 반영되었습니다.'],next:'plan'};s.screen='result';}else I.preparePlan(s);};
I.closeSeason=s=>{const changes=I.diff(s.seasonStart||I.metrics(s),I.metrics(s));s.reports.unshift({period:I.period(s),rows:changes,money:s.seasonMoney||null,tags:[...s.tags],plan:s.focusPlan});s.reports=s.reports.slice(0,74);s.seasonMoney=null;
s.strain=s.energy<15||s.stress>90?s.strain+1:Math.max(0,s.strain-1);s.obscurity=I.age(s)>=30&&s.brand<12&&s.fans<8?s.obscurity+1:0;
if(s.strain>=3)s.ending={title:'휴식이 필요했던 커리어',body:'컨디션 15 미만 또는 스트레스 90 초과가 세 시즌 누적되어 활동을 중단했습니다.'};if(s.rep<25)s.ending={title:'신뢰를 잃은 무대',body:'누적된 대응과 선택으로 인성이 25 아래까지 내려가 활동을 중단했습니다.'};if(s.obscurity>=4)s.ending={title:'세대교체 속 은퇴',body:'낮은 브랜드와 팬덤이 네 시즌 이어져, 회사가 활동을 정리했습니다.'};if(s.ending){I.finish(s);return;}
if(I.gates[s.season]){s.mode='gate';s.gate={at:s.season,turn:0,target:I.gates[s.season].target,hand:[]};s.score=0;s.focus=0;s.gate.hand=I.hand(s);s.screen='intro';return;}I.advance(s);};
I.next=s=>{if(s.screen==='intro'){s.screen='choice';return true;}if(s.screen!=='result')return false;switch(s.last.next){case 'proposal':{const ev=I.pickEvent(s);if(ev){s.mode='event';s.eventId=ev.id;s.screen='intro';}else I.closeSeason(s);break;}case 'close':I.closeSeason(s);break;case 'gateCard':s.gate.hand=I.hand(s);s.screen='choice';break;case 'gateFinish':if(s.score>=s.gate.target)I.advance(s);else{s.ending={title:'다음 무대를 기약하며',body:`${I.gates[s.gate.at].title}에서 ${I.number(s.score)}점. 기준 ${s.gate.target}점에 미치지 못했습니다.`};I.finish(s);}break;case 'plan':I.preparePlan(s);break;}return true;};
I.choose=(s,id)=>{if(s.screen!=='choice')return false;const dec=I.current(s),o=dec.options.find(o=>o.id===id);if(!o)return false;const before=I.metrics(s),notes=[];let next='close',money=null;
if(s.mode==='gate'){const stat=o.stat==='best'?Math.max(s.v,s.d,s.look):s[o.stat],weak=o.cost>0&&s.energy<o.cost,gain=stat*o.mult*(1+s.focus*.12)*(.95+I.random(s)*.1)*(weak?.55:1);s.score=I.round(s.score+gain);s.energy=I.clamp(s.energy-o.cost);s.focus+=o.focus||0;s.gate.turn++;next=s.gate.turn===3?'gateFinish':'gateCard';if(weak)notes.push('컨디션 부족으로 이번 카드의 점수 효율이 55%로 낮아졌습니다.');if(s.gate.turn===3){const bonus=I.gateBonus(s);s.score=I.round(s.score+bonus);notes.push(`태도·팀 준비 보너스 +${bonus}점 포함 · ${s.score>=s.gate.target?'평가 통과':'기준 미달'}`);}}
else{const out=I.project(s,o,I.random(s));for(const k of I.statKeys)s[k]=out.state[k];money=out.money;if(money)s.seasonMoney=money;if(o.tag){const old=s.tags.find(t=>I.roles.includes(t));if(old&&old!==o.tag&&I.roles.includes(o.tag))notes.push(I.tags[old].name+'의 성장 보정을 해제하고 새 포지션으로 전환했습니다.');I.addTag(s,o.tag);notes.push(`${I.tags[o.tag].name}: ${I.tags[o.tag].desc}`);}if(o.buff){s.buffs=s.buffs.filter(b=>b.source!==s.eventId);s.buffs.push({...o.buff,source:s.eventId,until:s.season+o.buff.duration});notes.push(o.future);}if(o.risk){if(I.random(s)<o.risk.chance){I.apply(s,o.risk.effect);notes.push('예고된 추가 위험이 발생했습니다.');}else notes.push('추가 위험은 이번에 발생하지 않았습니다.');}if(s.mode==='plan'){s.focusPlan=o.id;s.planCounts[o.id]=(s.planCounts[o.id]||0)+1;next='proposal';notes.push('반년의 기본 일정을 한 번에 진행했습니다.');}else{s.eventSeen[dec.id]={last:s.season,count:(s.eventSeen[dec.id]?.count||0)+1};if(dec.need)notes.push(`이 제안은 '${I.tags[dec.need].name}'을 선택했던 덕분에 도착했습니다.`);}if(!o.tag&&!o.buff&&o.future)notes.push(o.future);}
I.clean(s);s.choicesMade++;const rows=I.diff(before,I.metrics(s));s.last={title:o.name,actor:dec.org,rows,notes,money,next};I.log(s,o.name,rows.map(r=>`${I.labels[r.key]} ${r.delta>0?'+':''}${I.value(r.key,r.delta)}`).join(' · ')+(o.tag?` → ${I.tags[o.tag].name}`:''));s.screen='result';return true;};
I.autoChoice=s=>{const options=I.current(s).options;let best=options[0],score=-Infinity;for(const o of options){const p=I.preview(s,o);let n=0;for(const r of p){const d=(r.lo+r.hi)/2;n+=d*({energy:s.energy<45?2:.1,stress:s.stress>60?-1.5:-.15,rep:s.rep<65?1.1:.2,score:1,v:.7,d:.7,look:.6,team:.4,song:.5,fans:1,brand:.6,cash:.1,debt:-.15,focus:s.gate?.turn<2?7:0}[r.key]||0);}if(o.tag&&!s.tags.includes(o.tag))n+=5;if(o.buff)n+=4;if(o.risk)n-=5;if(n>score){score=n;best=o;}}return best.id;};
})(globalThis.ILR);
