(function(I){'use strict';
I.clone=x=>JSON.parse(JSON.stringify(x));
I.round=x=>Math.round(x*10)/10;
I.clamp=(x,a=0,b=100)=>Math.max(a,Math.min(b,x));
I.random=s=>{let x=s.seed|0;x^=x<<13;x^=x>>>17;x^=x<<5;s.seed=x>>>0;return s.seed/4294967296;};
I.age=s=>13+Math.floor(s.season/2);
I.period=s=>`${I.age(s)}세 ${s.season%2?'하반기':'상반기'}`;
I.stage=s=>s.season<2?'academy':s.season<4?'candidate':s.season<8?'trainee':s.season<10?'squad':'career';
I.stageName=s=>({academy:'입문',candidate:'연습 대기생',trainee:'기획사 연습생',squad:'데뷔조',career:'현역 활동'})[I.stage(s)];
I.number=n=>Number.isInteger(n)?String(n):Number(n).toFixed(1);
I.money=n=>n>=100?`${I.number(I.round(n/100))}억`:`${I.number(I.round(n*100))}만`;
I.value=(k,n)=>['cash','debt'].includes(k)?I.money(n):I.number(I.round(n))+(k==='fans'?'만':'');
I.callName=name=>{const c=name.charCodeAt(name.length-1);return name+(c>=44032&&c<=55203?((c-44032)%28?'아':'야'):' 씨');};
I.text=(s,t)=>t.replaceAll('{name}',s.name).replaceAll('{call}',I.callName(s.name));
I.metrics=s=>Object.fromEntries(I.statKeys.map(k=>[k,s[k]||0]));
I.clean=s=>{for(const k of I.statKeys){if(!Number.isFinite(s[k]))s[k]=0;s[k]=I.round(['fans','cash','debt','score','focus'].includes(k)?Math.max(0,s[k]):I.clamp(s[k]));}};
I.newGame=(name='하린',seed=Date.now())=>({version:I.version,name:name.trim().slice(0,8)||'하린',seed:(Number(seed)>>>0)||1,season:0,route:null,screen:'home',mode:'plan',v:28,d:28,look:32,rep:58,energy:80,stress:16,team:50,song:20,brand:0,fans:0,debt:0,cash:0,score:0,focus:0,tags:[],buffs:[],planCounts:{},eventSeen:{},history:[],reports:[],choicesMade:0,focusPlan:'v',strain:0,obscurity:0,last:null,ending:null});
I.growthRate=(s,k)=>1+s.tags.reduce((n,t)=>n+(I.tags[t]?.stat===k?I.tags[t].rate:0),0)+s.buffs.filter(b=>b.until>=s.season&&b.stat===k).reduce((n,b)=>n+b.rate,0);
I.apply=(s,effect,position=.5)=>{for(const [k,v]of Object.entries(effect||{})){let d=Array.isArray(v)?v[0]+(v[1]-v[0])*position:v;if(d>0&& !['cash','debt','score','focus'].includes(k))d*=I.growthRate(s,k);s[k]=(s[k]||0)+d;}I.clean(s);};
I.addTag=(s,t)=>{if(!t||s.tags.includes(t))return;if(I.roles.includes(t))s.tags=s.tags.filter(x=>!I.roles.includes(x));s.tags.push(t);};
I.settle=(s,kind)=>{if(!kind)return null;const gross={album:60+s.brand+s.fans*2,fans:20+s.fans*2,concert:(70+s.fans*7)*(s.tags.includes('dinner')?1.25:1),ads:50+s.brand*2}[kind];const costs={album:30,fans:6,concert:24+s.fans*.5,ads:10}[kind];const share=s.tags.includes('renewal')?.6:.5,members=s.tags.includes('solo')?1:5;
const available=Math.max(0,gross*share-costs)/members,shortfall=Math.max(0,costs-gross*share)/members,paid=Math.min(s.debt,available),net=available-paid;s.debt+=shortfall-paid;s.cash+=net;I.clean(s);return {gross:I.round(gross),share,members,costs:I.round(costs),personal:I.round(available),shortfall:I.round(shortfall),paid:I.round(paid),net:I.round(net)};};
I.effective=(s,o)=>{let e={...o.effect};if(s.mode==='plan'){if(I.stage(s)!=='career')e.debt=(e.debt||0)+(s.season<4?1.5:s.season<8?2.4:4.5);else{e.brand=(e.brand||0)-(I.age(s)>=30?2:1);e.energy=(e.energy||0)-(I.age(s)>=28?1:0);if(I.age(s)>=30)e.fans=Array.isArray(e.fans)?e.fans.map(n=>n-s.fans*.015):(e.fans||0)-s.fans*.015;}}return e;};
I.project=(s,o,position)=>{const n={...s};I.apply(n,I.effective(s,o),position);const money=I.settle(n,o.business);return {state:n,money};};
I.diff=(a,b)=>I.statKeys.filter(k=>Math.abs((b[k]||0)-(a[k]||0))>.049).map(k=>({key:k,before:a[k]||0,after:b[k]||0,delta:I.round((b[k]||0)-(a[k]||0))}));
I.preview=(s,o)=>{if(s.mode==='gate'){const c=o,stat=c.stat==='best'?Math.max(s.v,s.d,s.look):s[c.stat],weak=c.cost>0&&s.energy<c.cost;const base=stat*c.mult*(1+s.focus*.12)*(weak?.55:1);return [{key:'score',lo:I.round(base*.95+(s.gate.turn===2?I.gateBonus(s):0)),hi:I.round(base*1.05+(s.gate.turn===2?I.gateBonus(s):0))},{key:'energy',lo:I.clamp(s.energy-c.cost)-s.energy,hi:I.clamp(s.energy-c.cost)-s.energy},...(c.focus?[{key:'focus',lo:c.focus,hi:c.focus}]:[])];}
const a=I.project(s,o,0).state,b=I.project(s,o,1).state;return I.statKeys.map(k=>({key:k,lo:I.round(Math.min(a[k],b[k])-(s[k]||0)),hi:I.round(Math.max(a[k],b[k])-(s[k]||0))})).filter(x=>x.lo||x.hi);};
I.good=(k,d)=>['stress','debt'].includes(k)?d<0:d>0;
I.log=(s,title,detail)=>{s.history.unshift({period:I.period(s),title,detail});s.history=s.history.slice(0,120);};
I.validSave=s=>!!s&&s.version===I.version&&Number.isInteger(s.season)&&s.season>=0&&s.season<=74&&typeof s.name==='string'&&['intro','choice','result','ending'].includes(s.screen)&&['plan','event','gate'].includes(s.mode)&&Array.isArray(s.tags)&&s.tags.every(t=>I.tags[t])&&Array.isArray(s.buffs)&&Array.isArray(s.history)&&Array.isArray(s.reports)&&I.statKeys.every(k=>Number.isFinite(s[k]))&&I.routes.some(r=>r.id===s.route)&&(!s.eventId||I.events.some(e=>e.id===s.eventId))&&(!s.gate||[1,7,9].includes(s.gate.at));
})(globalThis.ILR);
