'use strict';
(() => {
const I=ILR;
I.newGame=(name='하린',seed=Date.now())=>({version:I.version,name:String(name).trim().slice(0,8)||'하린',rng:seed>>>0,season:0,stage:0,stageSeasons:0,step:'route',serial:0,route:'',track:'v',hand:[],plan:null,tags:[],buffs:[],seen:[],history:[],reports:[],decisions:0,company:'NOVA',group:'NEON:DAY',members:5,gateFailures:0,poorHealth:0,lowFans:0,v:28,d:28,vi:32,ch:55,cond:78,stress:18,team:48,song:22,fans:0,brand:0,debt:0,cash:0,rank:100,best:100,exam:null,last:null});
I.snapshot=s=>Object.fromEntries([...I.stats,'score','focus'].map(k=>[k,k==='score'||k==='focus'?(s.exam?.[k]||0):s[k]]));
I.apply=(s,e)=>{for(const [k,v] of Object.entries(e)){if(!I.stats.includes(k)||!Number.isFinite(v))throw Error('Invalid effect: '+k);s[k]=I.round(I.clamp(s[k]+v,0,['fans','debt','cash'].includes(k)?1e9:100));}};
I.diff=(a,b)=>Object.keys(a).filter(k=>Math.abs((b[k]||0)-a[k])>.04).map(k=>({key:k,before:a[k],after:b[k],delta:I.round(b[k]-a[k])}));
I.addTag=(s,tag)=>{if(!tag)return;if(I.tagGrowth[tag])s.tags=s.tags.filter(t=>!I.tagGrowth[t]);if(!s.tags.includes(tag))s.tags.push(tag);};
I.makeHand=s=>{const skills=['v','d','vi'].sort((a,b)=>s[a]-s[b]);const main=s[s.track]>=95?skills[0]:s.track;const other=skills.find(k=>k!==main);if(s.stage===3&&s[main]>=95)s.hand=['fans','money','care'];else{let alt=s.stage===3?['fans','money',other][s.season%3]:other;s.hand=[main,alt,'care'];}s.serial++;};
I.start=(s,route)=>{if(s.step!=='route')return false;const r=I.routes.find(x=>x.id===route);if(!r)return false;I.apply(s,r.effect);s.route=route;s.track=r.track;s.step='plan';I.makeHand(s);s.history.push({date:I.date(s),text:`${r.name}에서 첫 반년을 시작했다.`});return true;};
I.growth=(s,key)=>{const out={};for(const [stat,v] of Object.entries(I.planData[key].growth)){let rate=stat===key?.4:0;for(const tag of s.tags){if(I.tagGrowth[tag]===stat)rate+=.2;if(tag==='loyal'&&stat==='fans')rate+=.25;if(tag==='longrun'&&stat==='cond')rate+=.25;}for(const b of s.buffs)if(b.stat===stat&&b.left>0)rate+=b.rate;out[stat]=I.round(v*(1+rate));}if(s.stage===2)out.song=(out.song||0)+5;if(s.stage===3&&key!=='care')out.fans=(out.fans||0)+1;return out;};
I.planOption=(s,key)=>{const p=I.planData[key],t={...s},a=I.snapshot(t);I.apply(t,p.effect);const exact=I.diff(a,I.snapshot(t));const g=I.growth(t,key),b=I.snapshot(t);I.apply(t,g);return {id:key,name:p.name,icon:p.icon,effect:p.effect,exact,growth:I.diff(b,I.snapshot(t)),future:p.future};};
I.getOptions=s=>{if(s.step==='plan')return s.hand.map(k=>I.planOption(s,k));if(s.step==='event')return I.events.find(e=>e.id===s.eventId).options.map(o=>{const t={...s},a=I.snapshot(t);I.apply(t,o.effect);return {...o,icon:'↗',exact:I.diff(a,I.snapshot(t)),growth:[]};});if(s.step==='exam')return I.examOptions(s);return [];};
I.eventEligible=(s,e)=>s.stage>=e.min&&s.stage<=e.max&&!s.seen.includes(e.id)&&(!e.routes||e.routes.includes(s.route))&&(!e.minAge||I.age(s)>=e.minAge)&&(!e.maxAge||I.age(s)<=e.maxAge)&&(!e.minFans||s.fans>=e.minFans)&&(!e.requires||s.tags.includes(e.requires))&&(!e.track||e.track===s.track);
I.pickEvent=s=>{if(!(s.season===0||[2,4,6,7,8,11].includes(s.season)||s.season>=14&&s.season%4===2))return null;let pool=I.events.filter(e=>I.eventEligible(s,e));if(!pool.length)return null;pool.sort((a,b)=>(Number(!!b.requires)*3+Number(!!b.minAge)*2+Number(!!b.track))-(Number(!!a.requires)*3+Number(!!a.minAge)*2+Number(!!a.track)));const top=pool.filter(e=>Number(!!e.requires)*3+Number(!!e.minAge)*2+Number(!!e.track)===Number(!!pool[0].requires)*3+Number(!!pool[0].minAge)*2+Number(!!pool[0].track));return top[Math.floor(I.random(s)*top.length)];};
I.report=(s,before,title,note,next,advance=false)=>{const after=I.snapshot(s);s.last={date:I.date(s),title,note,changes:I.diff(before,after),next,advance,tags:[...s.tags],buffs:I.clone(s.buffs),money:s.ledger?I.clone(s.ledger):null};s.reports.push(I.clone(s.last));s.history.push({date:I.date(s),text:title+' — '+note});s.step='report';s.serial++;};
I.next=s=>{if(s.step!=='report')return false;const r=s.last;if(r.advance)s.season++;s.step=r.next;if(s.step==='plan'){s.plan=null;s.ledger=null;s.exam=null;I.makeHand(s);}else if(s.step==='exam'){if(!s.exam)I.startExam(s);s.serial++;}else{s.serial++;}return true;};
I.autoChoice=s=>{const opts=I.getOptions(s);if(!opts.length)return null;if(s.step==='plan'){if(s.cond<46||s.stress>62||s.stage===3&&s.ch<72)return 'care';if(s.stage===3&&s.hand.includes('fans')&&s.fans<60)return 'fans';if(s.stage===3&&s.hand.includes('money')&&s.debt>0)return 'money';return s.hand.includes(s.track)?s.track:s.hand[0];}if(s.step==='exam')return I.examAuto(s);const rank=o=>Object.entries(o.effect).reduce((n,[k,v])=>n+v*(k==='cond'?(s.cond<45?1.2:.15):k==='stress'?-.2:k==='ch'?.8:k==='debt'?-.2:1),0)+(o.tag&&I.tagGrowth[o.tag]===s.track?12:0)+(o.tag==='dinner'?35:0)+(o.buff?4:0);return [...opts].sort((a,b)=>rank(b)-rank(a))[0].id;};
})();
