'use strict';
(() => {
const I=ILR,o=I.option;
I.events.push(
{id:'part-conflict',min:2,max:2,title:'겹치는 파트',org:'{company} 제작팀',speaker:'데뷔조 매니저',quote:'둘 다 같은 파트를 원하고 있어. {call}, 녹음 전에 서로 역할을 정리하자.',hint:'내 파트와 팀의 완성도 중 무엇이 더 급할까?',options:[o('solo','내 파트를 주장',{v:4,team:-7,song:4},'vocalist',null,'메인보컬 방향으로 포지션 변경'),o('duet','파트를 나눈다',{team:8,song:6},'loyal',null,'팀 합을 살려 팬덤형 커리어'),o('rehearse','추가 녹음 제안',{song:10,cond:-7,debt:2},null,null,'추가 비용으로 곡 완성도 확보')]},
{id:'debut-song',min:2,max:2,title:'데뷔곡 콘셉트',org:'{company} A&R',speaker:'음악 프로듀서',quote:'데뷔곡을 받았어. {call}, 목소리로 남을지 무대로 남을지 의견을 듣고 싶다.',hint:'지금 키워온 강점을 데뷔곡에 어떻게 담을까?',options:[o('live','라이브 중심 편곡',{v:4,song:8,cond:-5},'vocalist',null,'메인보컬 방향 · OST 기회'),o('dance','퍼포먼스 강화',{d:4,song:8,cond:-6},'performer',null,'퍼포먼스 방향 · 안무 기회'),o('team','멤버 균형 편곡',{team:8,song:6,ch:2},'loyal',null,'팬덤형 방향 · 팬클럽 기회')]},
{id:'first-comeback',min:3,max:3,maxAge:25,title:'다음 컴백의 색',org:'{company} A&R',speaker:'제작 팀장',quote:'{name} 씨, 데뷔 이후 어떤 모습으로 기억되고 싶나요? 다음 반년의 제작 방향을 정합시다.',hint:'짧은 화제성과 오래 남는 실력이 다를 수도 있다.',options:[o('live','라이브 콘텐츠',{v:3,fans:2,cond:-5},'vocalist',null,'보컬 성장 +20% · OST 제안'),o('visual','비주얼 캠페인',{vi:3,brand:5,stress:5},'center',null,'광고 제안 해금'),o('fans','팬 참여 앨범',{fans:3,ch:2,brand:-2},'loyal',null,'팬 성장 +25% · 팬클럽 제안')]},
{id:'ost',min:3,max:3,requires:'vocalist',title:'OST 제안',org:'드라마 음악 제작사',speaker:'음악감독',quote:'메인보컬로 쌓은 라이브를 들었어요. {name} 씨 목소리로 엔딩곡을 녹음하고 싶습니다.',hint:'개인 기회와 팀 일정이 겹칠 때 우선순위는?',options:[o('solo','솔로로 녹음',{v:3,brand:6,cond:-7},null,{stat:'fans',rate:.3,left:2,label:'OST 유입'},'2반기 팬 성장 +30%'),o('duet','팀 듀엣을 제안',{team:6,fans:2,brand:2},'loyal',null,'팀 팬덤을 함께 키운다'),o('rest','이번에는 쉬어간다',{cond:12,stress:-6},'longrun',null,'개인 노출 대신 장기관리')]},
{id:'brand-campaign',min:3,max:3,requires:'center',title:'브랜드 캠페인',org:'{company} 광고사업팀',speaker:'광고 담당자',quote:'센터 활동이 광고주 눈에 들었어요. {name} 씨 단독 캠페인 일정을 잡아볼까요?',hint:'브랜드 상승이 내 정산으로 바로 이어지는 것은 아니다.',options:[o('exclusive','단독 캠페인',{brand:7,cond:-7,stress:5},null,{stat:'revenue',rate:.4,left:2,label:'광고 계약'},'2반기 매출 +40% · 비용 후 정산'),o('group','팀 광고로 전환',{brand:3,team:5,fans:1},'loyal',null,'개인 노출보다 팀 관계'),o('decline','컴백에 집중',{v:3,d:3,brand:-2},null,null,'광고 대신 기본기')]},
{id:'dance-project',min:3,max:3,requires:'performer',title:'안무 프로젝트',org:'{company} 퍼포먼스팀',speaker:'안무 디렉터',quote:'{name} 씨 리더 경험을 외부 무대에서도 보여주죠. 새 안무를 공동 제작해보면 어때요?',hint:'창작 경험은 남지만 준비 기간에는 체력이 든다.',options:[o('create','공동 안무 제작',{d:5,cond:-8,brand:4},null,{stat:'d',rate:.3,left:2,label:'창작 캠프'},'2반기 댄스 성장 +30%'),o('teach','동료들과 워크숍',{team:8,ch:3,cond:-3},'longrun',null,'팀과 함께 오래 가는 기반'),o('film','짧은 영상만 공개',{brand:4,fans:2,stress:3},'public',null,'노출 확대 · 평판 대응 사건')]},
{id:'fan-club',min:3,max:3,requires:'loyal',title:'공식 팬클럽',org:'{company} 팬마케팅팀',speaker:'팬클럽 운영자',quote:'꾸준한 소통 덕분에 오래 남는 팬이 늘었어요. {name} 씨, 정기 만남을 만들어볼까요?',hint:'유입 숫자와 팬이 남을 이유는 다르다.',options:[o('regular','정기 팬미팅',{fans:4,cond:-5},null,{stat:'fans',rate:.35,left:3,label:'팬클럽 결속'},'3반기 팬 성장 +35%'),o('content','온라인 콘텐츠',{fans:2,brand:3,stress:4},'public',null,'새 유입과 공개 노출'),o('letters','천천히 답장',{ch:4,stress:-5,fans:1},'longrun',null,'성장 속도보다 신뢰')]},
{id:'fan-response',min:3,max:3,requires:'public',title:'짧게 잘린 영상',org:'{company} 매니지먼트',speaker:'담당 매니저',quote:'{name} 씨, 팬사인회 영상이 맥락 없이 돌고 있어요. 팬에게 설명할 방식부터 정합시다.',hint:'해명 방식은 화제성뿐 아니라 신뢰에도 남는다.',options:[o('explain','맥락을 설명하고 사과',{ch:4,brand:-3,stress:-3},'loyal',null,'신뢰 회복 · 팬클럽 기회'),o('meeting','팬에게 직접 설명',{fans:2,ch:2,cond:-6},null,null,'시간과 체력으로 오해 해소'),o('silence','무대응을 택한다',{stress:5},null,null,'55%: 인성 -8 · 브랜드 -6')],risk:true}
);
})();
