'use strict';
(() => {
const I=ILR, o=I.option;
I.events.push(
{id:'voice-class',min:0,max:0,routes:['vocal','dance'],track:'v',title:'전문반 제안',org:'{school}',speaker:'담당 강사',quote:'{call}, 노래에 집중하겠다는 선택을 봤어. 전문반에서 네 목소리를 더 밀어볼까?',hint:'전문 코치의 도움과 추가 비용을 함께 생각하자.',options:[o('accept','보컬 전문반',{debt:3,cond:-3},'vocalist',{stat:'v',rate:.25,left:2,label:'전문 코치'},'보컬 제안 해금 · 2반기 성장 +25%'),o('stage','합동 무대부터',{d:4,team:5,stress:3},'performer',null,'안무·퍼포먼스 제안 해금'),o('balance','기초반 유지',{ch:3,cond:5},null,null,'추가 비용 없이 회복') ]},
{id:'dance-team',min:0,max:0,routes:['vocal','dance'],track:'d',title:'쇼케이스 크루',org:'{school}',speaker:'퍼포먼스 강사',quote:'{call}, 이번 쇼케이스의 앞자리를 맡아볼래? 연습량은 늘지만 관계자에게 보여줄 수 있어.',hint:'무대 경험은 기회지만 체력이 필요하다.',options:[o('lead','리더로 참가',{d:4,cond:-8},'performer',null,'안무 제안 해금 · 댄스 성장 +20%'),o('camera','영상 촬영 담당',{vi:4,stress:3},'center',null,'센터 제안 해금 · 비주얼 성장 +20%'),o('basic','기초 훈련 유지',{v:3,ch:2,cond:4},null,null,'부족한 보컬과 컨디션 보완')]},
{id:'camera-test',min:0,max:0,track:'vi',title:'프로필 테스트',org:'{school}',speaker:'캐스팅 담당자',quote:'{name} 씨, 카메라 앞에서 표정이 좋네요. 공개 프로필로 먼저 반응을 볼까요?',hint:'먼저 알려지면 팬도, 지켜보는 눈도 늘어난다.',options:[o('public','공개 프로필',{fans:1.5,brand:3,stress:4},'public',null,'공개 활동·평판 대응 이벤트 해금'),o('private','비공개 센터 테스트',{vi:4,cond:-4},'center',null,'센터·광고 제안 해금'),o('lesson','실력부터 보완',{v:4,d:3,debt:2},null,null,'노출 없이 기본기 보완')]},
{id:'school-letter',min:0,max:0,title:'관계자의 추천서',org:'{school}',speaker:'진로 담당자',quote:'{call}, 회사에 네 소개를 보내볼 수 있어. 장점을 강조할지, 더 준비할지 정하자.',hint:'기회를 빨리 잡을수록 준비에 쓸 시간은 짧아진다.',options:[o('recommend','추천을 부탁한다',{brand:4,stress:4},null,{stat:'vi',rate:.2,left:1,label:'카메라 특강'},'이번 반년 비주얼 성장 +20%'),o('workshop','유료 특강 참가',{v:3,d:3,debt:2},null,null,'두 실력 축을 함께 보완'),o('wait','기초를 더 다진다',{ch:3,cond:8},null,null,'노출 대신 컨디션 확보')]},
{id:'main-voice',min:1,max:2,track:'v',title:'메인보컬 후보',org:'{company} A&R',speaker:'A&R 팀장',quote:'{name} 씨 목소리를 팀의 중심으로 쓰고 싶어요. 대신 센터보다는 라이브에 시간을 써야 합니다.',hint:'하나의 포지션을 맡으면 다른 자리에 쓸 시간이 줄어든다.',options:[o('accept','메인보컬 도전',{v:5,cond:-6},'vocalist',null,'기존 포지션 교체 · 보컬 성장 +20%'),o('center','센터를 요청한다',{vi:4,team:-4},'center',null,'기존 포지션 교체 · 광고 제안 해금'),o('team','팀의 균형을 맡는다',{team:7,ch:3},'longrun',null,'회복 성장 +25% · 장기 활동 제안')]},
{id:'center-offer',min:1,max:2,track:'vi',title:'센터 테스트',org:'{company} 트레이닝팀',speaker:'트레이닝 팀장',quote:'다음 조합에는 시선을 잡는 멤버가 필요해. {call}, 센터 경쟁에 들어가볼래?',hint:'주목도와 팀 관계를 동시에 얻기는 어렵다.',options:[o('accept','센터 경쟁 수락',{vi:5,team:-6},'center',null,'센터 성장 +20% · 광고 제안 해금'),o('dance','퍼포먼스에 집중',{d:4,cond:-4},'performer',null,'댄스 성장 +20% · 안무 제안 해금'),o('support','팀의 연결 역할',{team:8,ch:3},'longrun',null,'관계와 장기관리 우선')]},
{id:'dance-role',min:1,max:2,track:'d',title:'안무 리더 제안',org:'{company} 퍼포먼스팀',speaker:'안무 디렉터',quote:'동작만 잘하는 것과 팀을 이끄는 건 달라. {call}, 이번 안무 연습을 맡아볼래?',hint:'책임은 부담이지만 팀에 필요한 사람이 될 수 있다.',options:[o('lead','안무 리더 수락',{d:4,stress:5},'performer',null,'댄스 성장 +20% · 댄스 프로젝트 해금'),o('pair','동료와 공동 담당',{team:7,d:2},null,null,'리더 대신 관계와 기본기'),o('private','개인 레슨 선택',{v:4,debt:2},null,{stat:'v',rate:.2,left:2,label:'개인 레슨'},'2반기 보컬 성장 +20%')]},
{id:'public-trainee',min:1,max:2,title:'공개 연습생',org:'{company} 홍보팀',speaker:'홍보 담당자',quote:'{name} 씨 연습 영상을 먼저 공개하자는 얘기가 나왔어요. 반응을 보며 데뷔를 준비할 수 있죠.',hint:'먼저 모은 팬은 자산이지만 실수도 기록된다.',options:[o('reveal','공개를 수락한다',{fans:2,brand:4,stress:5},'public',null,'노출 수익 +10% · 대응 사건 해금'),o('practice','비공개 훈련 유지',{v:4,cond:3},null,null,'팬 확보 대신 실력과 컨디션'),o('team','팀 영상만 공개',{fans:1,team:5},'loyal',null,'팬클럽 제안 해금 · 팬 성장 +25%')]}
);
})();
