'use strict';
(() => {
const I=ILR,o=I.option;
I.events.push(
{id:'tour',min:3,max:3,minFans:8,title:'첫 단독 투어',org:'공연 기획사',speaker:'투어 프로듀서',quote:'{name} 씨, 이제 티켓을 살 팬이 충분해요. 공연 규모와 몸 상태를 함께 보고 결정하죠.',hint:'큰 공연의 수익 뒤에는 준비 비용과 체력 소모가 있다.',options:[o('arena','공격적으로 확장',{fans:4,cond:-12,stress:6},null,{stat:'revenue',rate:.5,left:2,label:'투어 일정'},'2반기 매출 +50%'),o('small','작은 공연부터',{fans:3,ch:2,cond:-4},'loyal',null,'팬 성장 +25%'),o('rest','다음 기회로 미룬다',{cond:10,stress:-6,brand:-2},'longrun',null,'공연 대신 회복')]},
{id:'live-stage',min:3,max:3,title:'라이브 특별 무대',org:'방송 음악제작팀',speaker:'무대 PD',quote:'{name} 씨, 이번에는 생방송 라이브입니다. 돋보일 기회지만 편곡 난도를 조절할 수 있어요.',hint:'내 실력과 컨디션에 맞는 무대가 무엇일까?',options:[o('difficult','고난도 라이브',{v:4,cond:-7,brand:4},'vocalist',null,'보컬 중심 커리어'),o('stable','안정적인 편곡',{ch:3,brand:2,fans:1},'loyal',null,'신뢰와 팬덤을 조금씩'),o('dance','퍼포먼스 무대',{d:4,cond:-6,brand:3},'performer',null,'퍼포먼스 중심 커리어')]},
{id:'rest-camp',min:1,max:3,title:'휴식 일정 제안',org:'{company} 매니지먼트',speaker:'일정 매니저',quote:'{name} 씨, 일정 사이에 빈 주간을 확보했어요. 재정비할지 추가 일을 잡을지 정해주세요.',hint:'쉬는 시간도 다음 무대를 위한 선택이다.',options:[o('rest','회복에 사용',{cond:14,stress:-10},'longrun',null,'회복 성장 +25%'),o('train','개인 트레이닝',{v:4,d:3,cond:-5},null,{stat:'v',rate:.2,left:2,label:'집중 훈련'},'2반기 보컬 성장 +20%'),o('work','광고 촬영 추가',{brand:5,cond:-7,stress:4},null,{stat:'revenue',rate:.25,left:1,label:'단기 촬영'},'이번 반년 매출 +25%')]},
{id:'renewal',min:3,max:3,minAge:24,title:'재계약 조건',org:'{company} 경영지원팀',speaker:'계약 담당자',quote:'{name} 씨, 다음 계약을 이야기할 때예요. 회사의 지원과 독립 운영의 책임을 비교해보세요.',hint:'수익 배분이 좋아져도 직접 감당할 일이 늘 수 있다.',options:[o('stay','회사와 재계약',{brand:3,cond:5},null,{stat:'revenue',rate:.2,left:4,label:'재계약 지원'},'회사 배분 50% · 4반기 매출 +20%'),o('indie','독립 운영으로 전환',{debt:12,stress:8},'indie',null,'내 팀 배분 60% · 시즌 비용 +3백만'),o('short','짧은 계약으로 관망',{ch:3,stress:-4},'longrun',null,'기존 배분 유지 · 장기관리')]},
{id:'rookies',min:3,max:3,minAge:30,title:'신인에게 넘어간 예산',org:'{company} 전략기획팀',speaker:'기획 실장',quote:'신인 팀에 홍보비가 집중되고 있어요. {name} 씨는 기존 팬을 지킬지 새 이미지를 만들지 정해야 합니다.',hint:'신인을 따라갈 것인가, 나를 기다리는 관객을 남길 것인가?',options:[o('rebrand','새 이미지로 경쟁',{vi:4,brand:5,stress:7},'center',null,'비주얼 성장 +20% · 광고 방향'),o('loyal','기존 팬에게 집중',{fans:4,ch:3,brand:-2},'loyal',null,'팬 성장 +25% · 공연 방향'),o('skill','라이브 역량 재정비',{v:5,cond:6,brand:-3},'vocalist',null,'보컬 성장 +20% · OST 방향')]},
{id:'mentor',min:3,max:3,minAge:32,title:'후배의 특별 수업',org:'{company} 신인개발팀',speaker:'트레이닝 팀장',quote:'{name} 씨의 경험을 후배들에게 전해주면 좋겠어요. 현역 무대와 멘토 역할을 조율해봅시다.',hint:'나만의 무대를 지킬까, 오래 남을 관계를 만들까?',options:[o('teach','정기 멘토 수락',{ch:5,team:5,cond:-3},'longrun',null,'회복 성장 +25%'),o('collab','후배와 협업 무대',{brand:5,fans:2,stress:4},'public',null,'새 팬 유입과 노출'),o('solo','개인 무대에 집중',{v:4,cond:-4},'vocalist',null,'보컬 중심 커리어')]},
{id:'dinner',min:3,max:3,minAge:40,minFans:15,title:'디너쇼 제안',org:'장기 공연 기획사',speaker:'공연 대표',quote:'{name} 씨, 이제 이름을 보고 오는 관객이 있어요. 오래 함께할 디너쇼 무대로 옮겨볼까요?',hint:'유행의 중심을 내려놓아도 관객과 함께할 수 있다.',options:[o('accept','디너쇼 전환',{fans:3,brand:-4,debt:5},'dinner',null,'매출 +25% · 레전드 엔딩 조건'),o('tour','투어를 더 이어간다',{fans:4,cond:-10},null,{stat:'revenue',rate:.35,left:2,label:'앙코르 투어'},'2반기 매출 +35%'),o('prepare','보컬부터 정비',{v:5,cond:8},'longrun',null,'레전드에 필요한 라이브 기반')]},
{id:'archive',min:3,max:3,minAge:38,title:'오래된 노래의 재발견',org:'음반 유통사',speaker:'카탈로그 담당자',quote:'{name} 씨의 예전 노래를 찾는 사람이 늘었어요. 새로 녹음할지 그 시절 그대로 들려줄지 정해주세요.',hint:'새 팬의 유입과 오래된 팬의 추억을 어떻게 잇을까?',options:[o('record','새 라이브 버전',{v:4,cond:-5,fans:3},'vocalist',null,'라이브 중심 커리어'),o('memory','팬과 회고 콘텐츠',{ch:3,fans:4,stress:-3},'loyal',null,'팬 성장 +25%'),o('license','기존 음원 재발매',{brand:3},null,{stat:'revenue',rate:.25,left:3,label:'음원 재발매'},'3반기 매출 +25%')]}
);
})();
