'use strict';
(() => {
const I=ILR,e=I.escape;
I.changeHTML=x=>`<div class="change-row" data-result="${x.key}"><div>${I.labels[x.key]}${!['fans','cash','debt','score','focus'].includes(x.key)?`<div class="change-bar ${I.good(x.key,x.delta)?'':'loss'}"><i style="width:${x.before}%"></i><em data-bar-after="${x.after}" style="width:${x.before}%"></em></div>`:''}</div><b class="transition">${I.value(x.key,x.before)} → <strong>${I.value(x.key,x.after)}</strong></b><small class="${I.good(x.key,x.delta)?'positive':'negative'}">${x.delta>0?'+':''}${I.value(x.key,x.delta)}</small></div>`;
I.ledgerHTML=m=>m?`<div class="ledger">${[['팀 매출',m.gross],['회사 몫 '+Math.round(m.companyRate*100)+'%',m.company],['멤버 전체 몫',m.team],['제작·활동 비용',m.costs],['개인 몫 ('+m.members+'명 배분)',m.personal],['내 미정산 비용 상환',m.paid],['이번 내 정산',m.net]].map(([k,v])=>`<div><span>${k}</span><b>${I.money(v)}</b></div>`).join('')}</div>`:'<p class="report-meta">데뷔 전에는 육성 비용이 누적됩니다. 데뷔 후 수익에서 비용을 공제하고 멤버 수로 나눠 정산합니다.</p>';
I.reportHTML=s=>{const r=s.last;const nextLabel={event:'관련 제안 듣기',exam:s.exam&&s.exam.round<2?'다음 어필 준비':'평가 무대로',plan:'다음 반년으로',end:'커리어 돌아보기'}[r.next];return `<section class="report-view"><div class="eyebrow">RESULT · ${r.date}</div><h2>${e(r.title)}</h2><p class="report-meta">${e(r.note)}</p><article class="card"><h3>무엇이 달라졌을까?</h3><div class="changes" aria-live="polite">${r.changes.map(I.changeHTML).join('')||'<p>이번 선택에서는 수치 변화가 없습니다.</p>'}</div></article>${r.tags.length?`<article class="card"><h3>이어지는 커리어 방향</h3><div>${r.tags.map(t=>`<span class="tag">${I.tags[t]}</span>`).join('')}</div></article>`:''}${r.buffs.length?`<article class="card"><h3>다음 반기에도 남는 버프</h3>${r.buffs.map(b=>`<p>${e(b.label)} · ${b.left}반기 남음 · ${b.stat==='revenue'?'매출':I.labels[b.stat]} +${Math.round(b.rate*100)}%</p>`).join('')}</article>`:''}${r.money?`<article class="card"><h3>이번 반년 정산</h3>${I.ledgerHTML(r.money)}</article>`:''}<button class="primary" data-next>${nextLabel}<span>→</span></button><p class="report-meta">결과는 자동으로 사라지지 않아요. 하단 기록에서도 다시 볼 수 있습니다.</p>${I.footer()}</section>`;};
I.endingHTML=s=>`<section class="report-view"><div class="eyebrow">MY IDOL LIFE · ${I.age(s)}세</div><div class="ending-mark">${s.ending==='디너쇼 레전드'?'✦':'◇'}</div><h2>${e(s.ending)}</h2><p class="report-meta">${e(s.endNote)}</p><div class="info-grid">${[['내 누적 정산',I.money(s.cash)],['남은 미정산 비용',I.money(s.debt)],['팬덤',I.value('fans',s.fans)],['최고 브랜드 순위',s.stage===3?s.best+'위':'데뷔 전']].map(([k,v])=>`<div><span>${k}</span><b>${v}</b></div>`).join('')}</div><article class="card"><h3>내 인생을 바꾼 선택</h3>${s.history.filter(h=>h.text.startsWith('[분기]')).map(h=>`<div class="timeline"><small>${h.date}</small><p>${e(h.text.replace('[분기] ',''))}</p></div>`).join('')||'<p>첫 무대를 향한 도전이 기록으로 남았습니다.</p>'}</article><button class="primary" data-reset>새로운 인생 시작<span>↻</span></button></section>`;
I.panel=(s,kind)=>{
 if(kind==='stats')return ['상태와 버프',`<div class="info-grid">${I.stats.map(k=>`<div><span>${I.labels[k]}</span><b>${I.value(k,s[k])}</b></div>`).join('')}</div><h3 style="margin-top:18px">방향성</h3>${s.tags.map(t=>`<span class="tag">${I.tags[t]}</span>`).join('')||'<p class="report-meta">아직 포지션이 정해지지 않았어요.</p>'}<p class="report-meta">현재 성장 축: ${I.labels[s.track]}. 포지션 제안을 받으면 다음 사건과 성장률이 달라집니다.</p>${s.buffs.map(b=>`<p class="report-meta">${e(b.label)} · ${b.left}반기 · ${b.stat==='revenue'?'매출':I.labels[b.stat]} +${Math.round(b.rate*100)}%</p>`).join('')}`];
 if(kind==='history')return ['커리어 기록',s.reports.slice().reverse().map(r=>`<div class="timeline"><small>${r.date}</small><h3>${e(r.title)}</h3><p>${e(r.note)}</p>${r.changes.map(I.changeHTML).join('')}</div>`).join('')||'<p class="report-meta">첫 선택 후 변화가 여기에 기록됩니다.</p>'];
 if(kind==='money')return ['정산과 비용',I.ledgerHTML(s.ledger)+`<p class="report-meta">누적 정산 ${I.money(s.cash)} · 미정산 비용 ${I.money(s.debt)}</p><p class="report-meta">게임용 가상 계약입니다. 실제 연예계 계약을 일반화한 자료가 아닙니다.</p>`];
 const c=I.scene(s);return [c.title,`<div class="speaker"><div><small>${e(c.org)}</small><b>${e(c.speaker)}</b></div></div><p class="report-meta">“${e(c.quote)}”</p><p class="report-meta">(${e(c.hint)})</p><p class="report-meta">${e(c.cause)}</p>`];
};
})();
