'use strict';
(() => {
const I=ILR;
I.escape=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const e=I.escape;
I.chip=x=>`<span class="effect-chip ${I.good(x.key,x.delta)?'':'negative'}" data-stat="${x.key}">${I.labels[x.key]} ${x.delta>0?'+':''}${I.value(x.key,x.delta)}</span>`;
I.footer=()=>'<nav class="play-footer" aria-label="커리어 정보"><button data-info="stats">상태·버프</button><button data-info="history">기록·변화</button><button data-info="money">정산</button></nav>';
I.hud=s=>{let keys=s.step==='exam'?['score','focus','v','d']:s.stage===3?['fans','brand','ch','v']:s.stage===2?['v','d','team','song']:['v','d','vi','ch'];return `<div class="hud"><div class="hud-top">${keys.map(k=>`<div class="hud-stat" data-hud="${k}"><span>${I.labels[k]}</span><b>${I.value(k,k==='score'||k==='focus'?s.exam[k]:s[k])}</b></div>`).join('')}</div><div class="hud-meters">${['cond','stress'].map(k=>`<div data-hud="${k}"><div class="meter-line"><span>${I.labels[k]}${k==='cond'&&s[k]<20?' · 낮음':''}</span><b>${s[k]}</b></div><div class="meter-track ${k==='stress'?'risk':''}"><i style="width:${s[k]}%"></i></div></div>`).join('')}</div></div>`;};
I.seasonHead=s=>`<div class="season-head"><div><small>${e(s.name)} · ${I.stages[s.stage]}</small><h2>${I.date(s)}</h2></div><span class="pill">${s.step==='exam'?`평가 ${s.exam.round+1}/2`:s.step==='event'?'조직의 제안':'반년 계획'}</span></div>`;
I.introHTML=s=>{const c=I.scene(s);return `<section class="play intro-play">${I.seasonHead(s)}${I.hud(s)}<article class="dialogue-card"><div class="speaker"><div class="speaker-icon">${c.icon}</div><div><small>${e(c.org)}</small><b>${e(c.speaker)}</b></div></div><blockquote>“${e(c.quote)}”</blockquote><p class="thought">(${e(c.hint)})</p><p class="cause">${e(c.cause)}</p></article><button class="primary" data-reveal>어떻게 할까?<span>선택 보기 →</span></button>${I.footer()}</section>`;};
I.choicesHTML=s=>{const c=I.scene(s),opts=I.getOptions(s);return `<section class="play">${I.seasonHead(s)}${I.hud(s)}<div class="context-line"><span>${e(c.hint)}</span><button data-info="dialogue">대사 다시 보기</button></div><div class="decision-body"><div class="choice-heading"><h3>${e(c.title)}</h3><small>${s.step==='exam'?`목표 ${s.exam.target} · 보너스 ${I.examBonus(s)}`:'하나를 선택'}</small></div><div class="choice-grid">${opts.map(o=>`<button class="option" data-choice="${o.id}"><div class="option-top"><span class="glyph">${o.icon}</span><h3>${e(o.name)}</h3><span class="arrow">→</span></div><div class="effect-line">${o.range?`<span class="effect-chip">평가 예상 +${Math.floor(o.range[0])}~${Math.ceil(o.range[1])}</span>`:''}${o.exact.filter(x=>x.delta).map(I.chip).join('')||(!o.range?'<span class="effect-chip neutral">즉시 수치 변화 없음</span>':'')}</div>${o.growth.length?`<div class="growth-line">반년 성장 ${o.growth.map(x=>`${I.labels[x.key]} ${x.delta>0?'+':''}${I.value(x.key,x.delta)}`).join(' · ')}</div>`:''}<div class="future-line">${e(o.future)}</div></button>`).join('')}</div></div>${I.footer()}</section>`;};
I.routesHTML=()=>`<section class="play route-play"><div><div class="eyebrow">FIRST STEP</div><h2>어디에서 시작할까?</h2></div><p class="route-context">같은 중1, 다른 출발점.<br>먼저 키우고 싶은 강점으로 고르세요.</p><div class="routes-grid">${I.routes.map(r=>`<button class="option" data-route="${r.id}"><small class="eyebrow">${r.kind}</small><div class="option-top"><span class="glyph">${r.icon}</span><h3>${r.name}</h3></div><div class="effect-line">${Object.entries(r.effect).map(([k,v])=>I.chip({key:k,delta:v})).join('')}</div><div class="route-note">${r.org}</div><strong class="positive">이 루트로 시작 →</strong></button>`).join('')}</div><button class="secondary" data-home>이름 다시 정하기</button></section>`;
I.homeHTML=()=>`<section class="hero"><div class="eyebrow">NEW IDOL LIFE</div><h2>이번 생,<br>아이돌로 살아볼까요?</h2><p>학원의 첫 제안에서 마지막 디너쇼까지.<br>반년의 선택이 다음 기회를 만듭니다.</p><form id="start-form"><label for="player-name">무대에서 불릴 이름</label><input id="player-name" maxlength="8" value="하린" autocomplete="off" required><button class="primary" type="submit">새로운 인생 시작<span>→</span></button></form></section><section class="home-info"><div class="eyebrow">HOW TO PLAY</div><div class="card"><h3>제안을 듣고, 내 방향을 고르세요.</h3><p>관련 조직의 대사 → 판단 힌트 → 선택 → 실제 변화. 레슨 반복 대신 반년을 한 번에 진행합니다.</p></div><div class="card"><h3>상태와 결과는 언제든 확인</h3><p>선택 화면에는 세 선택지를 모두 모았습니다. 긴 기록과 정산은 따로 펼쳐봅니다.</p></div></section>`;
})();
