(function(I){
'use strict';
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const sign=(k,n)=>`${n>0?'+':''}${I.value(k,n)}`;
const tone=(k,n)=>n===0?'':(['stress','debt'].includes(k)?n<0:n>0)?'good':'bad';
const effect=(k,min,max=min)=>`<span class="effect ${tone(k,(min+max)/2)}">${I.labels[k]} ${sign(k,min)}${min!==max?'~'+sign(k,max):''}</span>`;
const btn=(text,id,cls='primary')=>`<button class="${cls}" data-command="${id}">${text}</button>`;
const call=n=>{const c=n.charCodeAt(n.length-1)-44032;return n+(c>=0&&c<11172&&c%28?'아':'야');};
const line=(t,s)=>esc(t.replaceAll('{name}',s.name).replaceAll('{call}',call(s.name)));
const changes=list=>list.map(x=>`<div class="change"><span>${I.labels[x.key]}</span><b><small>${I.value(x.key,x.before)} → </small><span data-count-key="${x.key}" data-from="${x.before}" data-to="${x.after}">${I.value(x.key,x.after)}</span></b><em class="${tone(x.key,x.delta)}">${sign(x.key,x.delta)}</em></div>`).join('');
const money=y=>y?`<section class="report-card"><h3>반년 정산 · 게임 내 가정</h3>${[['팀 매출',y.gross],['회사 몫',y.company],['제작·활동 비용',y.cost],['1인 배분액',y.distributable],['미정산 비용 상환',y.paid],['내 실수령',y.net],['추가 이월 비용',y.carry]].map(([k,v])=>`<div class="change"><span>${k}</span><b>${I.value('cash',v)}</b></div>`).join('')}<p class="muted">${y.members}인 배분. 회사 몫과 제작비를 차감한 뒤 인원수로 나누고, 개인 미정산 비용을 상환합니다. 실제 계약 일반화가 아닌 시뮬레이션 규칙입니다.</p></section>`:'';
I.V={esc,tone,changes,money,
home(hasSave){return `<div class="home-body"><section class="welcome"><p class="eyebrow">NEW IDOL LIFE</p><h2>이번 생,<br>어떤 무대에 설까요?</h2><p class="muted">반년의 선택이 모여 평생의 무대가 됩니다.</p><label>활동 이름<input id="playerName" class="name-field" value="하린" maxlength="8" autocomplete="off" enterkeyhint="go"></label>${btn('새로운 인생 시작 <span>→</span>','routes')}</section><div class="home-tiles">${hasSave?btn('<small>MY LIFE</small><b>이어서 하기 →</b>','resume',''):btn('<small>GAME FLOW</small><b>플레이 안내 →</b>','help','')}${btn('<small>BUILD 2.0.0</small><b>개선 내용 보기 →</b>','notes','')}</div><p class="home-note">학원 → 연습 대기생 → 연습생 → 데뷔조 → 현역 가수.<br>반년 계획은 한 번만 선택합니다. 같은 계획은 나중에 자동으로 유지할 수 있어요.</p><p class="version">HALF-YEAR EDITION · v${I.VERSION}</p></div>`;},
routes(){return `<section class="routes-page"><div><p class="eyebrow">FIRST STEP</p><h2>어디에서 시작할까요?</h2><p class="muted">첫 능력치와 첫 번째 제안자가 달라집니다.</p></div><div class="route-grid">${I.routes.map(r=>`<button class="route" data-route="${r.id}"><span class="route-icon">${r.icon}</span><b>${r.name}</b><div class="effects">${Object.entries(r.effect).map(([k,v])=>effect(k,v)).join('')}</div><small>이곳에서 시작 →</small></button>`).join('')}</div>${btn('← 이름 다시 입력','home','secondary')}</section>`;},
hud(s){const st=s.stats,keys=s.exam?['score','focus','v','ch']:s.season<8?['v','d','vi','ch']:['fans','brand','v','ch'];return `<div class="hud"><div class="stats-inline">${keys.map(k=>`<div class="stat" data-stat="${k}"><small>${I.labels[k]}</small><b>${I.value(k,st[k])}</b></div>`).join('')}</div><div class="meters">${['cond','stress'].map(k=>`<div data-stat="${k}"><div class="meter-label"><span>${I.labels[k]}${k==='cond'&&st[k]<30?' · 주의':''}</span><b>${st[k]}</b></div><div class="bar ${k==='stress'?'stress':''}"><i style="width:${I.clamp(st[k])}%"></i></div></div>`).join('')}</div></div>`;},
play(s,auto){const c=s.scene,previews=c.options.map(o=>I.preview(s,o));
 const common=previews[0].filter(x=>previews.every(p=>p.some(y=>y.key===x.key&&y.min===x.min&&y.max===x.max)));
 return `<section class="play"><div class="topline"><div><p class="eyebrow">${I.term(s)}</p><h2>${esc(c.title)}</h2><p class="stage-sub">${esc(c.reason)}</p></div><span class="pill">${s.exam?`${s.exam.turn+1}/2턴`:I.stageNames[I.stage(s)]}</span></div>${this.hud(s)}${!s.revealed?`<section class="intro"><div class="speaker"><div class="speaker-icon">${c.kind==='exam'?'★':'✦'}</div><div><small>${esc(c.org)}</small><b>${esc(c.speaker)}</b></div></div><p class="quote">“${line(c.line,s)}”</p><p class="thought">(${esc(c.hint)})</p>${btn('제안 살펴보기 <span>→</span>','reveal')}</section>`:`<section class="decisions"><div class="decision-head"><div><h3>${esc(c.org)}의 제안</h3><p>${esc(c.hint)}</p></div>${btn('대사<br>다시','dialogue','replay-line')}</div><p class="shared-effects">${s.exam?'이번 카드 · 종료 보너스 +'+I.round(s.stats.ch*.07+s.stats.team*.05+(s.exam.kind===2?s.stats.song*.15:0))+'점':'수치: 반년 전체'}${common.length?' · 공통 '+common.map(x=>`${I.labels[x.key]} ${sign(x.key,x.min)}`).join(' · '):' · ~는 예상 범위'}</p><div class="choices">${c.options.map((o,i)=>`<button class="choice" data-choice="${i}"><span class="choice-top"><span class="choice-icon">${o.icon||'✦'}</span><span class="choice-name">${esc(o.name)}</span><span class="choice-arrow">→</span></span><span class="effects">${previews[i].filter(x=>!common.some(y=>y.key===x.key)).map(x=>effect(x.key,x.min,x.max)).join('')}</span><span class="choice-future">${esc(o.future||'현재 성장 방향 유지')}</span></button>`).join('')}</div></section>`}<div class="toolbar">${btn('상태·버프','stats','')}${btn('기록','history','')}${btn(auto?'자동 정지':'자동 시연','auto',auto?'on':'')}</div></section>`;},
report(s,auto){const r=s.result;return `<section class="report"><div class="report-scroll"><p class="eyebrow">${esc(r.term)} · RESULT</p><h2>${esc(r.title)}</h2><p class="muted">${esc(r.reason)}</p>${r.milestone?`<p class="milestone">${esc(r.milestone)}</p>`:''}<section class="report-card"><h3>${r.money?'내 선택 + 기본 훈련':'반년 전체 변화'}</h3>${changes(r.money&&r.choiceChanges.length?r.choiceChanges:r.changes)}<p class="muted">선택 전 → 반영 후. 숫자는 실제 반영값입니다.</p></section>${r.future?`<section class="report-card"><h3>다음에 남는 영향</h3><p class="future muted">${esc(r.future)}</p></section>`:''}${money(r.money)}${r.money?`<section class="report-card"><h3>정산까지 마친 최종 변화</h3>${changes(r.changes)}</section>`:''}</div><nav class="report-nav">${auto?btn('자동 시연 정지','auto','secondary'):''}${btn(r.next==='end'?'커리어 결산 보기 →':r.next==='exam'?'관문 평가로 →':'다음으로 →','next')}${!s.exam&&I.age(s)>=18&&r.next==='scene'?btn('같은 계획으로 다음 제안까지 →','carry','secondary'):''}<p class="auto-note">${!s.exam&&I.age(s)>=18&&r.next==='scene'?'계획 유지: 최대 4년 · 반년마다 계산 · 제안·위험 시 중단':'결과는 기록에 남아요. 천천히 읽어도 괜찮아요.'}</p></nav></section>`;},
ending(s){return `<section class="report"><div class="report-scroll"><p class="eyebrow">CAREER RECORD · ${s.name?esc(s.name):''}</p><h2>${esc(s.ending)}</h2><p class="milestone">${I.age(s)}세 · ${Math.max(0,(s.season-8)/2)}년 활동 · 누적 정산 ${I.value('cash',s.stats.cash)}</p><section class="report-card"><h3>내가 선택한 방향</h3>${s.tags.map(t=>`<p class="log-item"><b>${I.tags[t].name}</b>${I.tags[t].desc}</p>`).join('')||'<p class="muted">아직 전문 포지션을 정하기 전의 인생이었어요.</p>'}</section><section class="report-card"><h3>이 인생을 바꾼 선택들</h3>${s.decisions.filter(d=>d.tag||d.title.includes('평가')||d.title.includes('무대')).map(d=>`<p class="log-item"><b>${d.term} · ${esc(d.choice)}</b>${esc(d.title)}<br>${esc(d.reason)}</p>`).join('')}</section></div><nav class="report-nav">${btn('다른 인생 준비하기 →','home')}</nav></section>`;}
};
})(globalThis.ILR);
