from playwright.sync_api import sync_playwright, expect
from pathlib import Path
import os, shutil
import json, traceback
ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'tests' / 'artifacts'
OUT.mkdir(parents=True, exist_ok=True)
HTML = (ROOT / 'public' / 'index.html').read_text()
results=[]; errors=[]
def ok(name, condition=True):
 assert condition, name
 results.append(name); print('PASS',name,flush=True)
def debug(page): return page.evaluate('window.__CLOUD_DEBUG__.getUX()')
def state(page): return page.evaluate('window.__CLOUD_DEBUG__.getState()')
def click(page, action):
 scope = page.locator('#dialog') if page.locator('#dialog').is_visible() else page
 scope.locator(f'[data-action="{action}"]:visible').first.click(timeout=5000)
def settle(page, ms=1400): page.clock.fast_forward(ms);page.wait_for_timeout(60)
def load(b, width=1440, height=960):
 page=b.new_page(viewport={'width':width,'height':height})
 page.on('pageerror', lambda e: errors.append(str(e)))
 page.clock.install()
 # about:blank has no persistent storage origin. The fixture stores only this test's data in memory.
 page.evaluate('''() => {for(const name of ['localStorage','sessionStorage']){const data=new Map();Object.defineProperty(window,name,{value:{getItem:k=>data.get(k)??null,setItem:(k,v)=>data.set(k,String(v)),removeItem:k=>data.delete(k)},configurable:true});}}''')
 page.set_content(HTML,wait_until='load');page.wait_for_timeout(80)
 return page
with sync_playwright() as p:
 b=p.chromium.launch(executable_path=os.environ.get('CHROMIUM_PATH') or shutil.which('chromium'),headless=True,args=['--no-sandbox'])
 page=load(b)
 ok('Home discloses only start, learn and menu; no name field or settings',page.locator('#nameInput').count()==0 and page.locator('[data-action="settings"]:visible').count()==0)
 click(page,'tutorial')
 settle(page,60000)
 ok('Lesson 1 has no deadline and only target 1 is enabled',debug(page)['tutorial']['stage']=='pick' and page.locator('[data-action="select"]:enabled').count()==1)
 click(page,'select'); settle(page)
 s=state(page);r=next(x for x in s['results'] if x['id']=='you')
 ok('Lesson 1 awards exactly 2 coins on a unique cloud',r['gain']==2 and not r['collision'])
 click(page,'lessonNext')
 ok('Lesson 2 selects only center, with all other controls disabled',page.locator('[data-action="select"]:enabled').get_attribute('data-cell')=='4')
 page.locator('[data-cell="4"]').click();settle(page)
 s=state(page);r=next(x for x in s['results'] if x['id']=='you')
 ok('Lesson 2 guarantees a collision but keeps previously earned coins',r['collision'] and r['gain']==0 and s['players'][0]['score']==2)
 page.screenshot(path=str(OUT/'cloud-pick-ux-tutorial.png'),full_page=True)
 click(page,'lessonNext')
 ok('Lesson 3 requires trying a different selection before lock',page.locator('[data-action="lock"]').is_disabled())
 page.locator('[data-cell="6"]').click()
 ok('First provisional selection does not move the character or reveal rivals',state(page)['phase']=='choose' and page.locator('[data-action="lock"]').is_disabled())
 page.locator('[data-cell="8"]').click()
 ok('Changing selection enables confirm',not page.locator('[data-action="lock"]').is_disabled())
 click(page,'lock');settle(page)
 ok('Lesson 3 preserves the changed and locked destination',next(x for x in state(page)['results'] if x['id']=='you')['cell']==8)
 click(page,'lessonNext');settle(page,25000)
 ok('Lesson 4 waits for the player to start the timer',debug(page)['tutorial']['stage']=='ready')
 click(page,'lessonTimed')
 page.locator('[data-cell="6"]').click()
 click(page,'menu'); t0=page.locator('#timerValue').inner_text(); settle(page,20000)
 ok('Tutorial menu pauses time and does not resolve the lesson',debug(page)['paused'] and debug(page)['tutorial']['stage']=='timed' and page.locator('#timerValue').inner_text()==t0)
 page.keyboard.press('Escape');settle(page,10500);settle(page)
 r=next(x for x in state(page)['results'] if x['id']=='you')
 ok('On timeout, the last unconfirmed choice is applied',r['cell']==6 and r['automatic'])
 click(page,'lessonRetry');click(page,'lessonTimed');settle(page,10500);settle(page)
 r=next(x for x in state(page)['results'] if x['id']=='you')
 ok('No selection gives zero, with retry offered',r['missed'] and r['gain']==0 and page.locator('[data-action="lessonRetry"]').is_visible())
 click(page,'lessonNext')
 ok('Tutorial completion screen offers practice or friends, and marks completion',debug(page)['screen']=='result' and debug(page)['learned'] and page.locator('[data-action="learnFriends"]').is_visible())
 page.screenshot(path=str(OUT/'cloud-pick-ux-tutorial-complete.png'),full_page=True)
 click(page,'learnFriends')
 ok('Friends setup explains missing server rather than failing on click',debug(page)['screen']=='setup' and page.locator('.server-offline').is_visible() and page.locator('[data-action="create"]').is_disabled())
 click(page,'kindSolo');page.locator('#nameInput').fill('밤친구')
 click(page,'settings');page.locator('#roundSetting').select_option('3');page.locator('#timeSetting').select_option('5');page.locator('#settingsForm button[type="submit"]').click()
 ok('Rules are configured in a secondary dialog, not on the home screen',not page.locator('#dialog').is_visible() and '3라운드 · 선택 5초' in page.locator('.setup-meta').inner_text())
 click(page,'solo');settle(page,2700)
 ok('Practice begins at 0 without tutorial scores',state(page)['phase']=='choose' and all(x['score']==0 for x in state(page)['players']))
 ok('In-game room settings and history do not clutter the main screen',page.locator('[data-action="settings"]:visible').count()==0 and page.locator('[data-action="history"]:visible').count()==0)
 page.screenshot(path=str(OUT/'cloud-pick-ux-play.png'),full_page=True)
 click(page,'menu');click(page,'motion');ok('Reduced motion can be toggled',page.evaluate('window.__CLOUD_DEBUG__.getTheme().reducedMotion'))
 click(page,'sound');ok('Sound can be muted',page.evaluate('window.__CLOUD_DEBUG__.getTheme().muted'))
 s0=state(page);settle(page,15000);ok('Practice menu pauses the local game',state(page)['round']==s0['round'] and state(page)['phase']==s0['phase'])
 page.keyboard.press('Escape');page.locator('#choiceBar').focus();page.keyboard.press('1');page.keyboard.press('Enter')
 ok('Keyboard 1 + Enter selects and confirms the legal cloud',state(page)['players'][0]['locked'] and state(page)['players'][0]['selected']==6)
 for _ in range(20):
  if state(page)['phase']=='finished':break
  settle(page,6500)
 ok('Practice completes to a separate result screen with a replay CTA',debug(page)['screen']=='result' and page.locator('[data-action="start"]:visible').is_visible())
 page.screenshot(path=str(OUT/'cloud-pick-ux-results.png'),full_page=True)
 click(page,'start');ok('Replay resets the game to round 1 and zero scores',state(page)['round']==1 and all(x['score']==0 for x in state(page)['players']))
 page.close()
 # Responsive tests on independent screens; no network or time fixture mutations to game code.
 for w,h in [(320,740),(390,844),(768,1024),(1024,768),(1440,960)]:
  q=load(b,w,h)
  if w==1440:q.screenshot(path=str(OUT/'cloud-pick-ux-home.png'),full_page=True)
  if w==390:q.screenshot(path=str(OUT/'cloud-pick-ux-mobile-home.png'),full_page=True)
  ok(f'Home fits viewport width {w}',q.evaluate('document.documentElement.scrollWidth<=innerWidth'))
  click(q,'tutorial')
  ok(f'Tutorial controls fit viewport width {w}',q.evaluate('document.documentElement.scrollWidth<=innerWidth'))
  if w==390:q.screenshot(path=str(OUT/'cloud-pick-ux-mobile-tutorial.png'),full_page=True)
  click(q,'menu');click(q,'leaveDialog');click(q,'leave');click(q,'setup');click(q,'solo');settle(q,2650)
  ok(f'Play screen fits viewport width {w}',q.evaluate('document.documentElement.scrollWidth<=innerWidth'))
  ok(f'Core selection targets are >=44px at {w}',q.locator('.pick-btn:visible').evaluate_all('(es)=>es.every(e=>{const r=e.getBoundingClientRect();return r.width>=44&&r.height>=44})'))
  if w==390:q.screenshot(path=str(OUT/'cloud-pick-ux-mobile-play.png'),full_page=True)
  q.close()
 ok('No unhandled browser JavaScript errors',not errors)
 b.close()
(OUT / 'ux-browser-results.json').write_text(json.dumps({'passed':results,'count':len(results),'errors':errors,'method':'Chromium DOM loaded with set_content; network server verified separately via Node real HTTP/SSE; in-memory storage fixture for about:blank'},ensure_ascii=False,indent=2))
print('TOTAL',len(results))
